use super::{addr_modes::AddrMode, instructions::Instruction};
use AddrMode::*;
use Instruction::*;

pub struct InstructionSummary {
    pub addr_mode: AddrMode,
    pub instruction: Instruction,
    pub cycles: u8,
}

impl InstructionSummary {
    pub fn new(addr_mode: AddrMode, instruction: Instruction, cycles: u8) -> Self {
        Self {
            addr_mode,
            cycles,
            instruction,
        }
    }
}

impl From<u8> for InstructionSummary {
    fn from(opcode: u8) -> Self {
        match opcode {
            0x00 => Self::new(Implied, BRK_ForceBreak, 7),
            0x01 => Self::new(IndirectOffsetX, ORA_ORMemoryWithAcc, 6),
            0x05 => Self::new(ZeroPage, ORA_ORMemoryWithAcc, 3),
            0x06 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 5),
            0x08 => Self::new(Implied, PHP_PushProcessorStatusOnStack, 3),
            0x09 => Self::new(Immediate, ORA_ORMemoryWithAcc, 2),
            0x0A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x0D => Self::new(Absolute, ORA_ORMemoryWithAcc, 4),
            0x0E => Self::new(Absolute, ASL_ShiftLeftOneBit, 6),

            0x10 => Self::new(Relative, BPL_BranchOnResultPlus, 2),
            0x11 => Self::new(IndirectOffsetY, ORA_ORMemoryWithAcc, 5),
            0x15 => Self::new(ZeroPageOffsetX, ORA_ORMemoryWithAcc, 4),
            0x16 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 6),
            0x18 => Self::new(Implied, CLC_ClearCarryFlag, 2),
            0x19 => Self::new(AbsoluteOffsetY, ORA_ORMemoryWithAcc, 4),
            0x1D => Self::new(AbsoluteOffsetX, ORA_ORMemoryWithAcc, 4),
            0x1E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 7),

            0x20 => Self::new(Absolute, JSR_JumpToSavingReturnAddr, 6),
            0x21 => Self::new(IndirectOffsetX, AND_AndBitwiseWithAcc, 6),
            0x24 => Self::new(ZeroPage, BIT_BitTestInMemoryWithAcc, 3),
            0x25 => Self::new(ZeroPage, AND_AndBitwiseWithAcc, 3),
            0x26 => Self::new(ZeroPage, ROL_RotateOneBitLeft, 5),
            0x28 => Self::new(Implied, PLP_PullProcessorStatusFromStack, 4),
            0x29 => Self::new(Immediate, AND_AndBitwiseWithAcc, 2),
            0x2A => Self::new(Implied, ROL_RotateOneBitLeft, 2),
            0x2C => Self::new(Absolute, BIT_BitTestInMemoryWithAcc, 4),
            0x2D => Self::new(Absolute, AND_AndBitwiseWithAcc, 4),
            0x2E => Self::new(Absolute, ROL_RotateOneBitLeft, 6),

            0x30 => Self::new(Relative, BMI_BranchOnResultMinus, 2),
            0x31 => Self::new(IndirectOffsetY, AND_AndBitwiseWithAcc, 5),
            0x35 => Self::new(ZeroPageOffsetX, AND_AndBitwiseWithAcc, 4),
            0x36 => Self::new(ZeroPageOffsetX, ROL_RotateOneBitLeft, 6),
            0x38 => Self::new(Implied, SEC_SetCarryFlag, 2),
            0x39 => Self::new(AbsoluteOffsetY, AND_AndBitwiseWithAcc, 4),
            0x3D => Self::new(AbsoluteOffsetX, AND_AndBitwiseWithAcc, 4),
            0x3E => Self::new(AbsoluteOffsetX, ROL_RotateOneBitLeft, 7),

            0x40 => Self::new(Implied, RTI_ReturnFromInterrupt, 6),
            0x41 => Self::new(IndirectOffsetX, EOR_ExclusiveORMemoryWithAcc, 6),
            0x45 => Self::new(ZeroPage, EOR_ExclusiveORMemoryWithAcc, 3),
            0x46 => Self::new(ZeroPage, LSR_ShiftOneBitRight, 5),
            0x48 => Self::new(Implied, PHA_PushAccOnStack, 3),
            0x49 => Self::new(Immediate, EOR_ExclusiveORMemoryWithAcc, 2),
            0x4A => Self::new(Implied, LSR_ShiftOneBitRight, 2),
            0x4C => Self::new(Absolute, JMP_JumpTo, 3),
            0x4D => Self::new(Absolute, EOR_ExclusiveORMemoryWithAcc, 4),
            0x4E => Self::new(Absolute, LSR_ShiftOneBitRight, 6),

            0x50 => Self::new(Relative, BVC_BranchOnOverflowClear, 2),
            0x51 => Self::new(IndirectOffsetX, EOR_ExclusiveORMemoryWithAcc, 5),
            0x55 => Self::new(ZeroPage, EOR_ExclusiveORMemoryWithAcc, 4),
            0x56 => Self::new(ZeroPage, LSR_ShiftOneBitRight, 6),
            0x58 => Self::new(Implied, CLI_ClearInterruptDisableBit, 2),
            0x59 => Self::new(AbsoluteOffsetY, EOR_ExclusiveORMemoryWithAcc, 4),
            0x5D => Self::new(AbsoluteOffsetX, EOR_ExclusiveORMemoryWithAcc, 4),
            0x5E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 7),

            0x60 => Self::new(Implied, RTS_ReturnFromSubroutine, 6),
            0x61 => Self::new(IndirectOffsetX, ADC_AddMemoryToAccWithCarry, 6),
            0x65 => Self::new(ZeroPage, ADC_AddMemoryToAccWithCarry, 3),
            0x66 => Self::new(ZeroPage, ROR_RotateOneBitRight, 5),
            0x68 => Self::new(Implied, PLA_PullAccFromStack, 4),
            0x69 => Self::new(Immediate, ADC_AddMemoryToAccWithCarry, 2),
            0x6A => Self::new(Implied, ROR_RotateOneBitRight, 2),
            0x6C => Self::new(Indirect, JMP_JumpTo, 5),
            0x6D => Self::new(Absolute, ADC_AddMemoryToAccWithCarry, 4),
            0x6E => Self::new(Absolute, ROR_RotateOneBitRight, 6),

            0x70 => Self::new(Relative, BVS_BranchOnOverflowSet, 2),
            0x71 => Self::new(IndirectOffsetY, ADC_AddMemoryToAccWithCarry, 5),
            0x75 => Self::new(ZeroPageOffsetX, ADC_AddMemoryToAccWithCarry, 4),
            0x76 => Self::new(ZeroPageOffsetX, ROR_RotateOneBitRight, 6),
            0x78 => Self::new(Implied, SEI_SetInterruptDisableStatus, 2),
            0x79 => Self::new(AbsoluteOffsetY, ADC_AddMemoryToAccWithCarry, 4),
            0x7D => Self::new(AbsoluteOffsetX, ADC_AddMemoryToAccWithCarry, 4),
            0x7E => Self::new(AbsoluteOffsetX, ROR_RotateOneBitRight, 7),

            0x81 => Self::new(IndirectOffsetX, STA_StoreAccInMemory, 6),
            0x84 => Self::new(ZeroPage, STY_StoreYInMemory, 3),
            0x85 => Self::new(ZeroPage, STA_StoreAccInMemory, 3),
            0x86 => Self::new(ZeroPage, STX_StoreXInMemory, 3),
            0x88 => Self::new(Implied, DEY_DecrementYByOne, 2),
            0x8A => Self::new(Implied, TXA_TransferXToAcc, 2),
            0x8C => Self::new(Absolute, STY_StoreYInMemory, 4),
            0x8D => Self::new(Absolute, STA_StoreAccInMemory, 4),
            0x8E => Self::new(Absolute, STX_StoreXInMemory, 4),

            0x90 => Self::new(Relative, BCC_BranchOnCarryClear, 2),
            0x91 => Self::new(IndirectOffsetY, STA_StoreAccInMemory, 6),
            0x94 => Self::new(ZeroPageOffsetX, STY_StoreYInMemory, 4),
            0x95 => Self::new(ZeroPageOffsetX, STA_StoreAccInMemory, 4),
            0x96 => Self::new(ZeroPageOffsetY, STX_StoreXInMemory, 4),
            0x98 => Self::new(Implied, TYA_TransferYToAcc, 2),
            0x99 => Self::new(AbsoluteOffsetY, STA_StoreAccInMemory, 5),
            0x9A => Self::new(Implied, TXS_TransferXToStackRegister, 2),
            0x9D => Self::new(AbsoluteOffsetX, STA_StoreAccInMemory, 5),

            0xA0 => Self::new(Immediate, LDY_LoadYWithMemory, 2),
            0xA1 => Self::new(IndirectOffsetX, LDA_LoadAccWithMemory, 6),
            0xA2 => Self::new(Immediate, LDX_LoadXWithMemory, 2),
            0xA4 => Self::new(ZeroPage, LDY_LoadYWithMemory, 3),
            0xA5 => Self::new(ZeroPage, LDA_LoadAccWithMemory, 3),
            0xA6 => Self::new(ZeroPage, LDX_LoadXWithMemory, 3),
            0xA8 => Self::new(Implied, TAY_TransferAccToY, 2),
            0xA9 => Self::new(Immediate, LDA_LoadAccWithMemory, 2),
            0xAA => Self::new(Implied, TAX_TransferAccToX, 2),
            0xAC => Self::new(Absolute, LDY_LoadYWithMemory, 4),
            0xAD => Self::new(Absolute, LDA_LoadAccWithMemory, 4),
            0xAE => Self::new(Absolute, LDX_LoadXWithMemory, 4),

            0xB0 => Self::new(Relative, BCS_BranchOnCarrySet, 2),
            0xB1 => Self::new(IndirectOffsetY, LDA_LoadAccWithMemory, 5),
            0xB4 => Self::new(ZeroPageOffsetX, LDY_LoadYWithMemory, 4),
            0xB5 => Self::new(ZeroPageOffsetX, LDA_LoadAccWithMemory, 4),
            0xB6 => Self::new(ZeroPageOffsetY, LDX_LoadXWithMemory, 4),
            0xB8 => Self::new(Implied, CLV_ClearOverflowFlag, 2),
            0xB9 => Self::new(AbsoluteOffsetY, LDA_LoadAccWithMemory, 4),
            0xBA => Self::new(Implied, TSX_TransferStackPointerToX, 2),
            0xBC => Self::new(AbsoluteOffsetX, LDY_LoadYWithMemory, 4),
            0xBD => Self::new(AbsoluteOffsetX, LDA_LoadAccWithMemory, 4),
            0xBE => Self::new(AbsoluteOffsetY, LDX_LoadXWithMemory, 4),

            0xC0 => Self::new(Relative, CPY_CompareMemoryAndY, 2),
            0xC1 => Self::new(IndirectOffsetY, CMP_CompareMemoryAndAcc, 6),
            0xC4 => Self::new(ZeroPage, CPY_CompareMemoryAndY, 3),
            0xC5 => Self::new(ZeroPage, CMP_CompareMemoryAndAcc, 3),
            0xC6 => Self::new(ZeroPage, DEC_DecrementMemoryByOne, 5),
            0xC8 => Self::new(Implied, INY_IncrementYByOne, 2),
            0xC9 => Self::new(Immediate, CMP_CompareMemoryAndAcc, 2),
            0xCA => Self::new(Implied, DEX_DecrementXByOne, 2),
            0xCC => Self::new(Absolute, CPY_CompareMemoryAndY, 4),
            0xCD => Self::new(Absolute, CMP_CompareMemoryAndAcc, 4),
            0xCE => Self::new(Absolute, DEC_DecrementMemoryByOne, 6),

            0xD0 => Self::new(Relative, BNE_BranchOnResultNotZero, 2),
            0xD1 => Self::new(IndirectOffsetY, CMP_CompareMemoryAndAcc, 5),
            0xD5 => Self::new(ZeroPageOffsetX, CMP_CompareMemoryAndAcc, 4),
            0xD6 => Self::new(ZeroPageOffsetX, DEC_DecrementMemoryByOne, 6),
            0xD8 => Self::new(Implied, CLD_ClearDecimalMode, 2),
            0xD9 => Self::new(AbsoluteOffsetY, CMP_CompareMemoryAndAcc, 4),
            0xDD => Self::new(AbsoluteOffsetX, CMP_CompareMemoryAndAcc, 4),
            0xDE => Self::new(AbsoluteOffsetX, DEC_DecrementMemoryByOne, 7),

            0xE0 => Self::new(Immediate, CPX_CompareMemoryAndX, 2),
            0xE1 => Self::new(IndirectOffsetX, SBC_SubtractMemoryFromAccWithBorrow, 6),
            0xE4 => Self::new(ZeroPage, CPX_CompareMemoryAndX, 3),
            0xE5 => Self::new(ZeroPage, SBC_SubtractMemoryFromAccWithBorrow, 3),
            0xE6 => Self::new(ZeroPage, INC_IncrementMemoryByOne, 5),
            0xE8 => Self::new(Implied, INX_IncrementXByOne, 2),
            0xE9 => Self::new(Immediate, SBC_SubtractMemoryFromAccWithBorrow, 2),
            0xEA => Self::new(Implied, NOP_NoOperation, 2),
            0xEC => Self::new(Absolute, CPX_CompareMemoryAndX, 4),
            0xED => Self::new(Absolute, SBC_SubtractMemoryFromAccWithBorrow, 4),
            0xEE => Self::new(Absolute, INC_IncrementMemoryByOne, 6),

            0xF0 => Self::new(Relative, BEQ_BranchOnResultZero, 2),
            0xF1 => Self::new(IndirectOffsetY, SBC_SubtractMemoryFromAccWithBorrow, 5),
            0xF5 => Self::new(ZeroPageOffsetX, SBC_SubtractMemoryFromAccWithBorrow, 4),
            0xF6 => Self::new(ZeroPageOffsetX, INC_IncrementMemoryByOne, 6),
            0xF8 => Self::new(Implied, SED_SetDecimalMode, 2),
            0xF9 => Self::new(AbsoluteOffsetY, SBC_SubtractMemoryFromAccWithBorrow, 4),
            0xFD => Self::new(AbsoluteOffsetX, SBC_SubtractMemoryFromAccWithBorrow, 4),
            0xFE => Self::new(AbsoluteOffsetX, INC_IncrementMemoryByOne, 7),

            _ => Self::new(Implied, InvalidInstruction, 2),
        }
    }
}
