use super::{addr_modes::AddrMode, instructions::Instruction};
use sdl2::sys::ZPixmap;
use AddrMode::*;
use Instruction::*;

pub struct InstructionSummary {
    pub addr_mode: AddrMode,
    pub instruction: Instruction,
    pub cycles: u8,
}

impl InstructionSummary {
    pub fn new(addr_mode: AddrMode, instruction: Instruction, cycles: u8) -> Self {
        Self {
            addr_mode,
            cycles,
            instruction,
        }
    }
}

impl From<u8> for InstructionSummary {
    fn from(opcode: u8) -> Self {
        match opcode {
            0x00 => Self::new(Implied, BRK_ForceBreak, 7),
            0x01 => Self::new(IndirectOffsetX, ORA_ORMemoryWithAcc, 6),
            0x05 => Self::new(ZeroPage, ORA_ORMemoryWithAcc, 3),
            0x06 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 5),
            0x08 => Self::new(Implied, PHP_PushProcessorStatusOnStack, 3),
            0x09 => Self::new(Immediate, ORA_ORMemoryWithAcc, 2),
            0x0A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x0D => Self::new(Absolute, ORA_ORMemoryWithAcc, 4),
            0x0E => Self::new(Absolute, ASL_ShiftLeftOneBit, 6),

            0x10 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0x11 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 3),
            0x15 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 4),
            0x16 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 6),
            0x18 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x19 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 4),
            0x1D => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 4),
            0x1E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 7),

            0x20 => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x21 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0x24 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x25 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x26 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x28 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x29 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0x2A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x2C => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x2D => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x2E => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0x30 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0x31 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0x35 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x36 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x38 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x39 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0x3D => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0x3E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            0x40 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x41 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0x45 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x46 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x48 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x49 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0x4A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x4C => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x4D => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x4E => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0x50 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0x51 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0x55 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x56 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x58 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x59 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0x5D => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0x5E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            0x60 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x61 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0x65 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x66 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x68 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x69 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0x6A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x6C => Self::new(Indirect, ASL_ShiftLeftOneBit, 2),
            0x6D => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x6E => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0x70 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0x71 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0x75 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x76 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x78 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x79 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0x7D => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0x7E => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            0x81 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0x84 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x85 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x86 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0x88 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x8A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x8C => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x8D => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0x8E => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0x90 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0x91 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0x94 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x95 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0x96 => Self::new(ZeroPageOffsetY, ASL_ShiftLeftOneBit, 2),
            0x98 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x99 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0x9A => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0x9D => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            0xA0 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xA1 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0xA2 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xA4 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xA5 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xA6 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xA8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xA9 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xAA => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xAC => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xAD => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xAE => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0xB0 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0xB1 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0xB4 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xB5 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xB6 => Self::new(ZeroPageOffsetY, ASL_ShiftLeftOneBit, 2),
            0xB8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xB9 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0xBA => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xBC => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0xBD => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0xBE => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),

            0xC0 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0xC1 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0xC4 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xC5 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xC6 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xC8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xC9 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xCA => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xCC => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xCD => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xCE => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0xD0 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0xD1 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0xD5 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xD6 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xD8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xD9 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0xDD => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0xDE => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            0xE0 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xE1 => Self::new(IndirectOffsetX, ASL_ShiftLeftOneBit, 2),
            0xE4 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xE5 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xE6 => Self::new(ZeroPage, ASL_ShiftLeftOneBit, 2),
            0xE8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xE9 => Self::new(Immediate, ASL_ShiftLeftOneBit, 2),
            0xEA => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xEC => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xED => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),
            0xEE => Self::new(Absolute, ASL_ShiftLeftOneBit, 2),

            0xF0 => Self::new(Relative, ASL_ShiftLeftOneBit, 2),
            0xF1 => Self::new(IndirectOffsetY, ASL_ShiftLeftOneBit, 2),
            0xF5 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xF6 => Self::new(ZeroPageOffsetX, ASL_ShiftLeftOneBit, 2),
            0xF8 => Self::new(Implied, ASL_ShiftLeftOneBit, 2),
            0xF9 => Self::new(AbsoluteOffsetY, ASL_ShiftLeftOneBit, 2),
            0xFD => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),
            0xFE => Self::new(AbsoluteOffsetX, ASL_ShiftLeftOneBit, 2),

            _ => Self::new(Implied, InvalidInstruction, 2),
        }
    }
}
